#!/bin/bash

# Wrapper for hypotheses_on_unclear.py

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT="$( dirname ${DIR} )"
export PYTHONPATH=${PYTHONPATH}:${PARENT}

exec python -m CBGM.hypotheses_on_unclear $@
